version: '3'

services:
    static-server:
        image: ghcr.io/brownhounds/go-static:latest
        environment:
            - PORT=8080
            - IS_SPA=true
            - SPA_ENTRYPOINT=index.html
            - STATIC_FOLDER=/app
            - PUBLIC_PATH=/
        volumes:
            - ./dist:/app
        ports:
            - 8080:8080
